#!/bin/bash
# this file exists because cron will strip all env, and thus php running from cron won't have the correct env and scripts will fail
# this is a better option than defining the env in the crontab file itself
# having in cronfile: BASH_ENV=/etc/elabftw_env /bin/bash -c 'php ...' didn't work.
if [ -f /etc/elabftw_env ]; then
    source /etc/elabftw_env
fi
/usr/bin/php81-real "$@"
